version: '2'
services:
  mysql:
    image: runner-image-mysql
    volumes:
      - runnerdata:/var/lib/mysql
    restart: 'always'
    expose:
    - '3307'
    ports:
    - '3307:3306'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - runner

  php:
    depends_on:
      - mysql
    user: root
    links:
      - mysql
    image: runner-image-php
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
    env_file: .env
    working_dir: /var/www/html
    networks:
      - runner

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      - runner

volumes:
    runnerdata:
      driver: local

networks:
  runner:
    driver: bridge
